invenio_records_permissions/version.py
setup.py

It goes in line with this https://github.com/inveniosoftware/invenio-records-permissions/issues/13
Need to release a new alpha

setup: remove unnecessary entry points

---

invenio_records_permissions/config.py
invenio_records_permissions/policies/records.py

- Another PR will be made to reflect this change in invenio-rdm-records
which will only be merged when a new release is made for this module
- closes #17

config: rename FACTORY to POLICY

---

invenio_records_permissions/version.py

Merging this one in immediately since release.

release: v1.0.0a3

---

invenio_records_permissions/policies/base.py
setup.py
tests/conftest.py
tests/test_permissions_base.py
tests/test_permissions_records.py

- Closes #8 : uses inherited explicit_excludes now
- Closes #9 : tests for that
- Closes #15 : uses invenio-access 1.3.0 to achieve it

excludes: exclude enabled [more]

---

invenio_records_permissions/api.py
invenio_records_permissions/generators.py
invenio_records_permissions/policies/base.py
invenio_records_permissions/policies/records.py
tests/test_generators.py
tests/test_permissions_base.py
tests/test_permissions_records.py

generators: implement Disable,SuperUser,defaults

---

setup.py

Changes:
- invenio-search
- invenio-db
- invenio-records-files
Ready for merge if all good.

dependencies: bump dependencies to comply with Invenio 3.2

---

invenio_records_permissions/__init__.py
invenio_records_permissions/factories/__init__.py
invenio_records_permissions/factories/records.py
invenio_records_permissions/policies/records.py
setup.py
tests/conftest.py
tests/test_factories_records.py

factories: Add files permission factory

---

invenio_records_permissions/factories/records.py
invenio_records_permissions/policies/records.py
tests/test_factories_records.py

factories: add download files case

---

docs/requirements.txt

docs: fix build requirements

---

invenio_records_permissions/version.py

closes https://github.com/inveniosoftware/invenio-records-permissions/issues/49

release: v0.8.0

---

invenio_records_permissions/__init__.py
invenio_records_permissions/factories/__init__.py
invenio_records_permissions/factories/records.py
invenio_records_permissions/policies/base.py
invenio_records_permissions/policies/deposits.py
invenio_records_permissions/policies/records.py
run-tests.sh
tests/conftest.py
tests/test_factories_records.py
tests/test_permissions_base.py

Rename can_list to can_search

---

invenio_records_permissions/version.py

breaking change: can_list -> can_search
merging when CI passes

release: v0.9.0

---

invenio_records_permissions/api.py
invenio_records_permissions/version.py
setup.py

Needed to progress on invenio-records-resources

release: v0.10.0

---

invenio_records_permissions/generators.py
tests/test_generators.py

generator: AuthenticatedUser

---

invenio_records_permissions/generators.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/400

generators: SystemProcess filter matchs all

---

invenio_records_permissions/generators.py
invenio_records_permissions/version.py

generator: fix query filter of superuser and system process

---

babel.ini
invenio_records_permissions/translations/messages.pot
setup.cfg

* remove jinja extensions
* adds fuzzy string true
* update .pot
related inveniosoftware/invenio-app-rdm#1664

i18n: update babel.ini

---

.github/workflows/tests.yml
docs/requirements.txt
invenio_records_permissions/api.py
invenio_records_permissions/generators.py
invenio_records_permissions/policies/base.py
requirements-devel.txt
run-tests.sh
setup.cfg
tests/conftest.py
tests/test_generators.py
tests/test_permissions_base.py

Requires https://github.com/inveniosoftware/invenio-search/pull/216

global: make search-engine-agnostic

---

invenio_records_permissions/generators.py

* closes https://github.com/inveniosoftware/invenio-requests/issues/280

generator: add system process w/o superuser

---

invenio_records_permissions/__init__.py
invenio_records_permissions/generators.py
tests/conftest.py
tests/test_generators.py
tests/test_permissions_base.py
tests/test_record_permission_policy.py

On @fenekku feedback, this PR renames the test superuser and role to hopefully be more clear. Please add any comment.

tests: improve naming

---

invenio_records_permissions/__init__.py
setup.cfg

* tests: upgrade invenio-accounts

setup: upgrade invenio-access

---

tests/test_generators.py

:heart: Thank you for your contribution!
Add tests for conditional generators :angel: 
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to …

tests: add conditional generator testcases

---

invenio_records_permissions/policies/records.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1479

records: add read deleted files permission

---

setup.cfg

* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2924
* This removes the dependency to invenio-admin.

installation: bump invenio-access

---

.github/workflows/pypi-publish.yml
CHANGES.rst
invenio_records_permissions/__init__.py
setup.cfg

- setup: pin dependencies
- setup: change to reusable workflows
- release: v0.22.0

pin dependencies

---

CHANGES.rst
invenio_records_permissions/__init__.py
setup.cfg

- setup: bump major dependencies
- setup: change to reusable workflows
- release: v1.0.0

bump major
